const pages=document.querySelectorAll('.page'), nav=document.querySelectorAll('.nav-item');
function showPage(id){pages.forEach(p=>p.classList.toggle('active-page',p.id===id));nav.forEach(n=>n.classList.toggle('active',n.dataset.page===id));window.scrollTo({top:0,behavior:'smooth'});document.querySelector('.sidebar').classList.remove('open')}
nav.forEach(n=>n.addEventListener('click',()=>showPage(n.dataset.page)));
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.go)));
document.getElementById('menuBtn').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));
document.getElementById('themeBtn').addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.theme=document.body.classList.contains('dark')?'dark':'light'});
if(localStorage.theme==='dark')document.body.classList.add('dark');
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
document.querySelectorAll('.submit-btn').forEach(b=>b.addEventListener('click',e=>{const row=e.target.closest('.assignment');row.dataset.status='submitted';row.querySelector('.pill').textContent='Submitted';row.querySelector('.pill').className='pill submitted';e.target.textContent='Done';e.target.classList.add('disabled');e.target.disabled=true;updatePending();toast('Assignment marked as submitted.')}));
function updatePending(){document.getElementById('pendingCount').textContent=document.querySelectorAll('.assignment[data-status="pending"]').length+1}
updatePending();
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const f=btn.dataset.filter;document.querySelectorAll('.assignment').forEach(a=>a.style.display=(f==='all'||a.dataset.status===f)?'flex':'none')}));
document.getElementById('courseFilter').addEventListener('change',e=>{const f=e.target.value;document.querySelectorAll('.course-card').forEach(c=>c.style.display=(f==='All Courses'||c.dataset.cat===f)?'block':'none')});
document.getElementById('noticeSearch').addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.notice-card').forEach(n=>n.style.display=n.innerText.toLowerCase().includes(q)?'flex':'none')});
document.getElementById('globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){const q=e.target.value.toLowerCase();const target=[...pages].find(p=>p.innerText.toLowerCase().includes(q));if(target){showPage(target.id);toast('Showing results in '+target.id)}}});
const modal=document.getElementById('modal');
document.getElementById('addAssignment').onclick=()=>modal.classList.add('show');
document.getElementById('closeModal').onclick=()=>modal.classList.remove('show');
document.getElementById('saveAssignment').onclick=()=>{const name=document.getElementById('newAssignName').value.trim(),date=document.getElementById('newAssignDate').value;if(!name||!date){toast('Please enter assignment name and due date.');return}const row=document.createElement('div');row.className='assignment';row.dataset.status='pending';row.innerHTML=`<div class="assign-icon orange-bg">NEW</div><div class="assign-main"><b>${name}</b><span>Student-created task • Due ${new Date(date+'T00:00:00').toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}</span><div class="assign-progress"><i style="width:5%"></i></div></div><span class="pill pending">Pending</span><button class="small-btn submit-btn">Submit</button>`;document.getElementById('assignmentList').appendChild(row);row.querySelector('.submit-btn').onclick=function(){row.dataset.status='submitted';row.querySelector('.pill').textContent='Submitted';row.querySelector('.pill').className='pill submitted';this.textContent='Done';this.disabled=true;this.classList.add('disabled');updatePending();toast('Assignment marked as submitted.')};modal.classList.remove('show');document.getElementById('newAssignName').value='';document.getElementById('newAssignDate').value='';updatePending();toast('Assignment added successfully.')};
document.getElementById('editProfile').onclick=()=>{const n=prompt('Enter your name:',document.getElementById('profileName').textContent);if(n&&n.trim()){document.getElementById('profileName').textContent=n.trim();toast('Profile updated successfully.')}};
